services:
  frontend:
    container_name: frontend-facturacion
    build: 
      context: ./apps/frontend
    volumes: 
      - ./apps/frontend:/app
      - /app/node_modules
    ports: 
      - "3001:4001"
    networks:
      - facturacion-net
      
  backend:
    container_name: backend-facturacion
    build: 
      context: ./apps/backend
    volumes: 
      - ./apps/backend:/app
      - /app/node_modules
    ports: 
      - "5001:5001"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - facturacion-net

  mysql:
    image: mysql:8.0
    container_name: database-facturacion
    user: "1000:1000"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: Facturacion_DB
    ports:
      - "3307:3306"
    volumes:
      - ./services/mysql/data:/var/lib/mysql
      - ./apps/init:/docker-entrypoint-initdb.d
      - ./services/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - facturacion-net
    healthcheck:
      test: ["CMD", "sh", "-c", "mysql -uroot -e 'USE Facturacion_DB; SHOW TABLES;'"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  facturacion-net:
    driver: bridge